name: Write tree structure to README
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate tree structure
        run: |
          echo "# Repository Tree Structure\n" > README.md
          tree -a -n -I '.git|node_modules' >> README.md
          sed -i 's/\t/    /g' README.md
      - name: Overwrite README
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "Overwrite README with tree structure"
          git push