name: Write tree structure to README
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write tree structure to README
        run: |
          echo '# ${{ github.repository }}' > README.md
          echo '### File structure' >> README.md
          echo '```' >> README.md
          tree -a -I '.*|node_modules' >> README.md
          echo '```' >> README.md
      - name: Push changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "Overwrite README with tree structure"
          git push